<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Backend\Api\" />
      <Folder Include="Backend\Config\" />
      <Folder Include="Backend\Core\" />
      <Folder Include="Frontend\assets\" />
      <Folder Include="Frontend\lib\core\" />
      <Folder Include="Frontend\lib\models\" />
      <Folder Include="Frontend\lib\services\" />
      <Folder Include="Frontend\lib\utils\" />
    </ItemGroup>

</Project>
