<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Frontend\lib\core\" />
      <Folder Include="Frontend\lib\models\" />
      <Folder Include="Frontend\lib\services\" />
      <Folder Include="Frontend\lib\utils\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    </ItemGroup>

</Project>